### ISSUE TITLE
Server crashes when running commands from item

### ISSUE THREAD

**Issue by Manicarus** [CamperSamu/ItemCommander#15]
## Server Specification

Docker containerized server using [itzg/docker-minecraft-server](https://github.com/itzg/docker-minecraft-server) image
Minecraft Fabric 1.19.2

## Steps to Reproduce

1. On item minecraft:paper execute:
```
/commander create "/help" KEEP PLAYER
```
2. Right Click the item(minecraft:paper)
3. Server crashes

The problem persists with other items.

## Questions

The mod version doesn't perfectly match the version of the server. Could this be the problem?

A bit off topic, but could the updated version of the mod(1.19) be uploaded to Modrinth? The latest version there is only compatible with 1.18 and command usage is different with current version.

## Crash Log

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-05-01 13:27:47
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
	at com.campersamu.itemcommander.nbt.Commander.executeCommand(Commander.java:181)
	at com.campersamu.itemcommander.nbt.Commander.executeCommand(Commander.java:227)
	at net.minecraft.class_3225.handler$zmi000$itemcommander$checkInteraction(class_3225.java:1531)
	at net.minecraft.class_3225.method_14256(class_3225.java:288)
	at net.minecraft.class_3244.method_12065(class_3244.java:1182)
	at net.minecraft.class_2886.method_12550(class_2886.java:29)
	at net.minecraft.class_2886.method_11054(class_2886.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.1.0-0.deb11.5-amd64
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 597261144 bytes (569 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Pentium(R) CPU G4600 @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4895.30
	Virtual memory used (MB): 8506.77
	Swap memory total (MB): 975.00
	Swap memory used (MB): 975.00
	JVM Flags: 2 total; -Xmx2G -Xms2G
	Fabric Mods: 
		architectury: Architectury 6.5.69
		areas: Areas 4.3
		cobblemon: Cobblemon 1.3.1+1.19.2
		collective: Collective 6.53
		ctov: ChoiceTheorem's Overhauled Villages 3.2.0
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.19
		fwaystones: Fabric Waystones (Polymer Port) 3.0.0-polymerport.0
			hologram-api: Hologram API 0.2.2+1.19
		goml: Get Off My Lawn ReServed 1.6.4+1.19.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
			common-protection-api: Common Protection API 1.0.0
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			playerabilitylib: Pal 1.6.0
			polymer: Polymer (Core) 0.2.25+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
			server_translations_api: Server Translations API 1.4.18+1.19.2
			sgui: sgui 1.1.5+1.19.1
		incendium: Incendium 5.1.6
		itemcommander: Item Commander 1.4.0
		java: OpenJDK 64-Bit Server VM 17
		keepinvcontrol: Keepinvcontrol 1.0.0
		lithium: Lithium 0.11.1
		luckperms: LuckPerms 5.4.66
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		minecraft: Minecraft 1.19.2
		nullscape: Nullscape 1.2.1
		randomvillagenames: Random Village Names 3.2
		spark: spark 1.10.37
		taterzens: Taterzens 1.11.1
			config2brigadier: Config to Brigadier 1.2.1
		terralith: Terralith 2.3.7b
		tradernpcs: Trader NPCs 1.2.0
		universal_shops: Universal Shops 1.0.2+1.19.2
			common-economy-api: Common Economy API 1.0.0
		villagespawnpoint: Village Spawn Point 4.0
		welcomemessage: Welcome Message 2.1
	Server Running: true
	Player Count: 1 / 4; [class_3222['Chalankoe'/75, l='ServerLevel[world]', x=14.40, y=73.94, z=799.24]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by CamperSamu** [comment]
I am currently lacking the time to officially update all my mods, that's why I don't have public releases for 1.19.x.

There's a 1.19.2 build on the Fabric Serverside Discord, but it's not 1.19.4 compatible.

**Comment by Manicarus** [comment]
Ahh okay, then I'll just wait for the official release. Thank you for replying back though.

**Comment by CamperSamu** [comment]
Sadly I got really, really busy so I kinda forgot/didn't have the practical time to finish the port, but I just updated it to 1.20.4 (801b538ff9146a8e6881580b0dc4a94f7946675b)
